FROM python:3.11-slim-bullseye

WORKDIR /usr/src/app

COPY code/. . && \
    code/requirements.txt ./

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0"]
